Description: Template to create an EC2 instance

Resources:
  # Defining the EC2 instance
  FridayHITTPrivateEC2Instance: #Instance Name cannot contain Spaces or Special Characters. Only Alphanumeric
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro  # Choose the instance type (e.g., t2.micro)
      KeyName: StormHawker_FridayHITT  # Replace with your EC2 key pair name
      ImageId: ami-00385a401487aefa4  # Replace with a valid AMI ID for your region
      Region: eu-west-1
